# Generated by Django 4.0.6 on 2023-02-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(max_length=104, upload_to='media/categories/'),
        ),
    ]
