# Generated by Django 4.0.6 on 2023-02-27 04:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 4, 52, 36, 734874, tzinfo=utc)),
        ),
    ]
